package com.zhupeiting.bisheproject.mapper;

import com.zhupeiting.bisheproject.model.Users;
import com.zhupeiting.bisheproject.model.UsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_USER
     *
     * @mbg.generated Wed Oct 19 18:00:58 CST 2022
     */
    long countByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_USER
     *
     * @mbg.generated Wed Oct 19 18:00:58 CST 2022
     */
    int deleteByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_USER
     *
     * @mbg.generated Wed Oct 19 18:00:58 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_USER
     *
     * @mbg.generated Wed Oct 19 18:00:58 CST 2022
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_USER
     *
     * @mbg.generated Wed Oct 19 18:00:58 CST 2022
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_USER
     *
     * @mbg.generated Wed Oct 19 18:00:58 CST 2022
     */
    List<Users> selectByExampleWithRowbounds(UsersExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_USER
     *
     * @mbg.generated Wed Oct 19 18:00:58 CST 2022
     */
    List<Users> selectByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_USER
     *
     * @mbg.generated Wed Oct 19 18:00:58 CST 2022
     */
    Users selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_USER
     *
     * @mbg.generated Wed Oct 19 18:00:58 CST 2022
     */
    int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_USER
     *
     * @mbg.generated Wed Oct 19 18:00:58 CST 2022
     */
    int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_USER
     *
     * @mbg.generated Wed Oct 19 18:00:58 CST 2022
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MY_USER
     *
     * @mbg.generated Wed Oct 19 18:00:58 CST 2022
     */
    int updateByPrimaryKey(Users record);
}